[2025-03-20T06:24:17.173+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T06:24:17.190+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_docling.trigger_github_workflow manual__2025-03-20T06:24:16.191044+00:00 [queued]>
[2025-03-20T06:24:17.201+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_docling.trigger_github_workflow manual__2025-03-20T06:24:16.191044+00:00 [queued]>
[2025-03-20T06:24:17.202+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-20T06:24:17.219+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): trigger_github_workflow> on 2025-03-20 06:24:16.191044+00:00
[2025-03-20T06:24:17.226+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=370) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-20T06:24:17.227+0000] {standard_task_runner.py:72} INFO - Started process 371 to run task
[2025-03-20T06:24:17.228+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_docling', 'trigger_github_workflow', 'manual__2025-03-20T06:24:16.191044+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_docling.py', '--cfg-path', '/tmp/tmph__5iv_q']
[2025-03-20T06:24:17.229+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask trigger_github_workflow
[2025-03-20T06:24:17.283+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_etl_docling.trigger_github_workflow manual__2025-03-20T06:24:16.191044+00:00 [running]> on host d7eb6e5bc173
[2025-03-20T06:24:17.424+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_etl_docling' AIRFLOW_CTX_TASK_ID='trigger_github_workflow' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T06:24:16.191044+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T06:24:16.191044+00:00'
[2025-03-20T06:24:17.433+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-20T06:24:17.466+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-20T06:24:17.471+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            curl -X POST             -H "Accept: application/vnd.github+json"             -H "Authorization: Bearer $GITHUB_BEARER_TOKEN"             https://api.github.com/repos/bigdata-org/AI_Powered_Information_Retrieval/actions/workflows/etl_docling.yaml/dispatches             -d \'{"ref": "main"}\'\n        ']
[2025-03-20T06:24:17.489+0000] {subprocess.py:99} INFO - Output:
[2025-03-20T06:24:17.511+0000] {subprocess.py:106} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2025-03-20T06:24:17.514+0000] {subprocess.py:106} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2025-03-20T06:24:17.762+0000] {subprocess.py:106} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   124  100   109  100    15    432     59 --:--:-- --:--:-- --:--:--   494
[2025-03-20T06:24:17.763+0000] {subprocess.py:106} INFO - {
[2025-03-20T06:24:17.764+0000] {subprocess.py:106} INFO -   "message": "Bad credentials",
[2025-03-20T06:24:17.765+0000] {subprocess.py:106} INFO -   "documentation_url": "https://docs.github.com/rest",
[2025-03-20T06:24:17.766+0000] {subprocess.py:106} INFO -   "status": "401"
[2025-03-20T06:24:17.767+0000] {subprocess.py:106} INFO - }
[2025-03-20T06:24:17.768+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-20T06:24:17.820+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-20T06:24:17.821+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_etl_docling, task_id=trigger_github_workflow, run_id=manual__2025-03-20T06:24:16.191044+00:00, execution_date=20250320T062416, start_date=20250320T062417, end_date=20250320T062417
[2025-03-20T06:24:17.855+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T06:24:17.875+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-20T06:24:17.879+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
