[2025-03-20T02:06:03.206+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T02:06:03.234+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_mistralAi.check_meatadata manual__2025-03-20T02:05:53.011228+00:00 [queued]>
[2025-03-20T02:06:03.248+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_mistralAi.check_meatadata manual__2025-03-20T02:05:53.011228+00:00 [queued]>
[2025-03-20T02:06:03.249+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-20T02:06:03.266+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): check_meatadata> on 2025-03-20 02:05:53.011228+00:00
[2025-03-20T02:06:03.276+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=523) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-20T02:06:03.279+0000] {standard_task_runner.py:72} INFO - Started process 525 to run task
[2025-03-20T02:06:03.279+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_mistralAi', 'check_meatadata', 'manual__2025-03-20T02:05:53.011228+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_mistralai.py', '--cfg-path', '/tmp/tmpsg3ger76']
[2025-03-20T02:06:03.281+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask check_meatadata
[2025-03-20T02:06:03.340+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_etl_mistralAi.check_meatadata manual__2025-03-20T02:05:53.011228+00:00 [running]> on host 0767c9e71a25
[2025-03-20T02:06:03.506+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_etl_mistralAi' AIRFLOW_CTX_TASK_ID='check_meatadata' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T02:05:53.011228+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T02:05:53.011228+00:00'
[2025-03-20T02:06:03.508+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-20T02:06:03.550+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-03-20T02:06:04.124+0000] {python.py:240} INFO - Done. Returned value was: etl_mistralAi
[2025-03-20T02:06:04.125+0000] {branch.py:38} INFO - Branch into etl_mistralAi
[2025-03-20T02:06:04.126+0000] {skipmixin.py:230} INFO - Following branch ('etl_mistralAi',)
[2025-03-20T02:06:04.146+0000] {skipmixin.py:278} INFO - Skipping tasks [('scrape_pdf_inks', -1)]
[2025-03-20T02:06:04.184+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-20T02:06:04.186+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_etl_mistralAi, task_id=check_meatadata, run_id=manual__2025-03-20T02:05:53.011228+00:00, execution_date=20250320T020553, start_date=20250320T020603, end_date=20250320T020604
[2025-03-20T02:06:04.223+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T02:06:04.258+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-20T02:06:04.261+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
